 
export enum ResourceCategory {
  CLOTHING = 'CLOTHING',
  FOOD = 'FOOD',
  TOOLS = 'TOOLS',
  TOYS = 'TOYS',
  FURNITURE = 'FURNITURE',
  ELECTRONICS = 'ELECTRONICS',
  BOOKS = 'BOOKS',
  HYGIENE = 'HYGIENE',
  SCHOOL_SUPPLIES = 'SCHOOL_SUPPLIES',
  OTHERS = 'OTHERS'
}
